--Task: Analyze Active Accounts by Type
--
--Write a query to summarize active accounts using CTEs.
--Requirements:
--- Group accounts by type (savings/checking)
--- Count active accounts for each type
--- Find most recent transaction date per type
--- Only include accounts with transactions from 2023
--- Use CTE to handle the initial account activity analysis
--- Sort results by account type
--- Consider transaction dates for activity status
--
--Expected columns: account_type, active_account_count, most_recent_transaction
