--Task: Create Employee Portfolio Performance Report
--
--Write a query to analyze employee performance metrics using CTEs.
--Requirements:
--- Display employee's first and last name
--- Count unique accounts managed by each employee
--- Calculate total portfolio balance under management
--- Count approved loans processed
--- Consider only accounts and loans in employee's branch
--- Use COALESCE for handling null balances
--- Sort by portfolio balance in descending order
--- Use CTE for metric calculations
--
--Expected columns: first_name, last_name, accounts_managed, loans_processed, portfolio_balance
