--Task: Calculate Customer Transaction Totals Using CTE
--Requirements:
--- Use CTE to calculate transaction totals per customer
--- Show customer name and their total transaction amount
--- Basic CTE example
--- Sort by total amount
--
--Expected columns: first_name, last_name, total_amount
